services:

  myapp:
    image: rapidcopy/stage/deb
    container_name: rapidcopy_stage_deb
    build:
      context: ../../../..
      dockerfile: src/docker/stage/deb/Dockerfile
    tty: true
    tmpfs:
      - /run
      - /run/lock
    security_opt:
      - seccomp:unconfined
    volumes:
      - type: bind
        source: ${RAPIDCOPY_DEB}
        target: /install/rapidcopy.deb
        read_only: true

      - type: bind
        source: /sys/fs/cgroup
        target: /sys/fs/cgroup
        read_only: true
